### ISSUE TITLE
[bug]: failure after upgrading to 4.0

### ISSUE THREAD

**Issue by outnsp** [nextcloud/context_chat_backend#114]
**Describe the bug**
the ExApp context_chat_backend not working anymore

**Context Chat Backend logs (if applicable, from the docker container)**
<details>
2024-12-18T13:14:45.351506509Z sudo: unable to resolve host context_chat_backend: Temporary failure in name resolution
2024-12-18T13:14:45.363462826Z The files belonging to this database system will be owned by user "postgres".
2024-12-18T13:14:45.363488571Z This user must also own the server process.
2024-12-18T13:14:45.363491242Z
2024-12-18T13:14:45.363492965Z The database cluster will be initialized with locale "C".
2024-12-18T13:14:45.363495414Z The default text search configuration will be set to "english".
2024-12-18T13:14:45.363497245Z
2024-12-18T13:14:45.363498771Z Data page checksums are disabled.
2024-12-18T13:14:45.363493938Z initdb: error: could not access directory "/nc_app_context_chat_backend_data/vector_db_data/pgsql": Permission denied
2024-12-18T13:14:45.363500435Z
</details>

**Setup Details (please complete the following information):**
 - Nextcloud Version: 30.0.2
 - AppAPI Version: 4.0
 - Nextcloud deployment method: nginx
 - Context Chat Backend deployment method: occ app_api:app:register context_chat_backend

**Comment by kyteinsky** [comment]
hello, we're preparing a fix for this. Please do the following in the meantime:
```
occ app_api:app:unregister context_chat_backend --rm-data
occ app_api:app:register context_chat_backend
```
Don't be alarmed, 4.0.0 introduces breaking changes that will clear the db anyway.

**Comment by outnsp** [comment]
thanks for the quick response
follow up failure
<details>
2024-12-18T15:13:02.098693441Z TRACE:    127.0.0.1:48980 - HTTP connection made
2024-12-18T15:13:02.099551372Z TRACE:    127.0.0.1:48980 - ASGI [4820] Started scope={'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 23000), 'client': ('127.0.0.1', 48980), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/updateAccessDeclarative', 'raw_path': b'/updateAccessDeclarative', 'query_string': b'', 'headers': '<...>', 'state': {}}
2024-12-18T15:13:02.100092712Z TRACE:    127.0.0.1:48980 - ASGI [4820] Receive {'type': 'http.request', 'body': '<504 bytes>', 'more_body': False}
2024-12-18T15:13:02.100657131Z TRACE:    127.0.0.1:48980 - ASGI [4820] Send {'type': 'http.response.start', 'status': 422, 'headers': '<...>'}
2024-12-18T15:13:02.100672266Z INFO:     127.0.0.1:48980 - "POST /updateAccessDeclarative HTTP/1.1" 422 Unprocessable Entity
2024-12-18T15:13:02.100750142Z TRACE:    127.0.0.1:48980 - ASGI [4820] Send {'type': 'http.response.body', 'body': '<558 bytes>'}
2024-12-18T15:13:02.100804062Z TRACE:    127.0.0.1:48980 - ASGI [4820] Completed
2024-12-18T15:13:17.118001586Z TRACE:    127.0.0.1:48980 - HTTP connection lost
</details>

an other function response is ok - example
<details>
2024-12-18T15:04:02.373007677Z TRACE:    127.0.0.1:39966 - HTTP connection made
2024-12-18T15:04:02.374060128Z TRACE:    127.0.0.1:39966 - ASGI [4816] Started scope={'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 23000), 'client': ('127.0.0.1', 39966), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/deleteSources', 'raw_path': b'/deleteSources', 'query_string': b'', 'headers': '<...>', 'state': {}}
2024-12-18T15:04:02.374885585Z TRACE:    127.0.0.1:39966 - ASGI [4816] Receive {'type': 'http.request', 'body': '<42 bytes>', 'more_body': False}
2024-12-18T15:04:02.375809635Z Delete sources request: ['files__default: 20914177']
2024-12-18T15:04:02.718377277Z TRACE:    127.0.0.1:39966 - ASGI [4816] Send {'type': 'http.response.start', 'status': 200, 'headers': '<...>'}
2024-12-18T15:04:02.718444126Z INFO:     127.0.0.1:39966 - "POST /deleteSources HTTP/1.1" 200 OK
2024-12-18T15:04:02.718614327Z TRACE:    127.0.0.1:39966 - ASGI [4816] Send {'type': 'http.response.body', 'body': '<39 bytes>'}
2024-12-18T15:04:02.718718012Z TRACE:    127.0.0.1:39966 - ASGI [4816] Completed
2024-12-18T15:04:17.729482970Z TRACE:    127.0.0.1:39966 - HTTP connection lost
</details>

**Comment by outnsp** [comment]
here the nextcloud log
<details>
{"reqId":"ZM1W6z4sGrwZQndiIb0p","level":3,"time":"2024-12-18T15:13:01+01:00","remoteAddr":"","user":"--","app":"context_chat","method":"","url":"--","message":"Error received from Context Chat Backend (ExApp)","userAgent":"--","version":"30.0.2.3","data":{"app":"context_chat","code":"422","response":"{\"detail\":[{\"type\":\"list_type\",\"loc\":[\"body\",\"userIds\"],\"msg\":\"Input should be a valid list\",\"input\":{\"0\":\"PLACEHOLDER - HERE STANDS A NAME OF AN USER\",\"1\":\"PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER\",\"2\":\"PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER\",\"4\":\"PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER\"}}]}"}}
</details>

**Comment by kyteinsky** [comment]
Thanks a lot for the logs! This has been fixed here https://github.com/nextcloud/context_chat/pull/87
And will be released in 4.0.1

**Comment by kyteinsky** [comment]
Please open a separate issue if you find more bugs. Or feel free to comment here if this issue is not fixed still.

**Comment by outnsp** [comment]
maybe a is this a follow up failure of the fix

docker-log
<details>
2024-12-20T15:59:02.450655894Z TRACE:    127.0.0.1:33132 - HTTP connection made
2024-12-20T15:59:02.451626883Z TRACE:    127.0.0.1:33132 - ASGI [3087] Started scope={'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 23000), 'client': ('127.0.0.1', 33132), 'scheme': 'http', 'method': 'POST', 'root_path': '', 'path': '/updateAccessDeclarative', 'raw_path': b'/updateAccessDeclarative', 'query_string': b'', 'headers': '<...>', 'state': {}}
2024-12-20T15:59:02.452009600Z TRACE:    127.0.0.1:33132 - ASGI [3087] Receive {'type': 'http.request', 'body': '<585 bytes>', 'more_body': False}
2024-12-20T15:59:02.452651872Z Update access declarative request: ['PLACEHOLDER - HERE STANDS A NAME OF AN USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER', 'PLACEHOLDER - HERE STANDS A NAME OF AN OTHER USER'] files__default: 20985843
2024-12-20T15:59:02.802057076Z Try 0 failed in exception
2024-12-20T15:59:06.211719715Z original traceback: Traceback (most recent call last):
2024-12-20T15:59:06.211742516Z   File "/app/context_chat_backend/utils.py", line 94, in exception_wrap
2024-12-20T15:59:06.211744939Z     resconn.send({ 'value': fun(*args, **kwargs), 'error': None })
2024-12-20T15:59:06.211746388Z                             ^^^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.211747626Z   File "/app/context_chat_backend/vectordb/service.py", line 55, in decl_update_access
2024-12-20T15:59:06.211748909Z     db.decl_update_access(user_ids, source_id)
2024-12-20T15:59:06.211750035Z   File "/app/context_chat_backend/vectordb/pgvector.py", line 202, in decl_update_access
2024-12-20T15:59:06.211751355Z     raise SafeDbException('Error: source id not found', 404)
2024-12-20T15:59:06.211752540Z context_chat_backend.vectordb.types.SafeDbException: ('Error: source id not found', 404)
2024-12-20T15:59:06.211753806Z
2024-12-20T15:59:06.212920421Z --- Logging error ---
2024-12-20T15:59:06.214374498Z Traceback (most recent call last):
2024-12-20T15:59:06.214640972Z   File "/usr/local/lib/python3.11/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2024-12-20T15:59:06.214661959Z     await app(scope, receive, sender)
2024-12-20T15:59:06.214667042Z   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 73, in app
2024-12-20T15:59:06.214671113Z     response = await f(request)
2024-12-20T15:59:06.214674581Z                ^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214678145Z   File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 301, in app
2024-12-20T15:59:06.214681942Z     raw_response = await run_endpoint_function(
2024-12-20T15:59:06.214685327Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214688752Z   File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
2024-12-20T15:59:06.214692539Z     return await run_in_threadpool(dependant.call, **values)
2024-12-20T15:59:06.214753641Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214765784Z   File "/usr/local/lib/python3.11/dist-packages/starlette/concurrency.py", line 39, in run_in_threadpool
2024-12-20T15:59:06.214768662Z     return await anyio.to_thread.run_sync(func, *args)
2024-12-20T15:59:06.214771026Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214773090Z   File "/usr/local/lib/python3.11/dist-packages/anyio/to_thread.py", line 56, in run_sync
2024-12-20T15:59:06.214775043Z     return await get_async_backend().run_sync_in_worker_thread(
2024-12-20T15:59:06.214776845Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214778597Z   File "/usr/local/lib/python3.11/dist-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
2024-12-20T15:59:06.214793544Z     return await future
2024-12-20T15:59:06.214795386Z            ^^^^^^^^^^^^
2024-12-20T15:59:06.214797067Z   File "/usr/local/lib/python3.11/dist-packages/anyio/_backends/_asyncio.py", line 1005, in run
2024-12-20T15:59:06.214799011Z     result = context.run(func, *args)
2024-12-20T15:59:06.214800705Z              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214802370Z   File "/app/context_chat_backend/controller.py", line 163, in wrapper
2024-12-20T15:59:06.214804258Z     return func(*args, **kwargs)
2024-12-20T15:59:06.214805947Z            ^^^^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214807624Z   File "/app/context_chat_backend/controller.py", line 198, in _
2024-12-20T15:59:06.214809486Z     exec_in_proc(target=decl_update_access, args=(vectordb_loader, userIds, sourceId))
2024-12-20T15:59:06.214811379Z   File "/app/context_chat_backend/utils.py", line 117, in exec_in_proc
2024-12-20T15:59:06.214813292Z     raise result['error']
2024-12-20T15:59:06.214815153Z context_chat_backend.vectordb.types.SafeDbException: ('Error: source id not found', 404)
2024-12-20T15:59:06.214817099Z
2024-12-20T15:59:06.214818710Z During handling of the above exception, another exception occurred:
2024-12-20T15:59:06.214820583Z
2024-12-20T15:59:06.214824968Z Traceback (most recent call last):
2024-12-20T15:59:06.214826670Z   File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
2024-12-20T15:59:06.214828683Z     msg = self.format(record)
2024-12-20T15:59:06.214830493Z           ^^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214832089Z   File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
2024-12-20T15:59:06.214833870Z     return fmt.format(record)
2024-12-20T15:59:06.214835483Z            ^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214837196Z   File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
2024-12-20T15:59:06.214838949Z     record.message = record.getMessage()
2024-12-20T15:59:06.214840684Z                      ^^^^^^^^^^^^^^^^^^^
2024-12-20T15:59:06.214842532Z   File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
2024-12-20T15:59:06.214844409Z     msg = msg % self.args
2024-12-20T15:59:06.214846041Z           ~~~~^~~~~~~~~~~
2024-12-20T15:59:06.214847610Z TypeError: not all arguments converted during string formatting
2024-12-20T15:59:06.214849400Z Call stack:
2024-12-20T15:59:06.214954286Z   File "/app/./main.py", line 19, in <module>
2024-12-20T15:59:06.214961102Z     uvicorn.run(
2024-12-20T15:59:06.214964467Z   File "/usr/local/lib/python3.11/dist-packages/uvicorn/main.py", line 579, in run
2024-12-20T15:59:06.214968730Z     server.run()
2024-12-20T15:59:06.214991576Z   File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 66, in run
2024-12-20T15:59:06.214998070Z     return asyncio.run(self.serve(sockets=sockets))
2024-12-20T15:59:06.215003977Z   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
2024-12-20T15:59:06.215007773Z     return runner.run(main)
2024-12-20T15:59:06.215010841Z   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
2024-12-20T15:59:06.215014210Z     return self._loop.run_until_complete(task)
2024-12-20T15:59:06.215017460Z   File "/usr/local/lib/python3.11/dist-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
2024-12-20T15:59:06.215021370Z     result = await app(  # type: ignore[func-returns-value]
2024-12-20T15:59:06.215024745Z   File "/usr/local/lib/python3.11/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2024-12-20T15:59:06.215028466Z     return await self.app(scope, receive, send)
2024-12-20T15:59:06.215031659Z   File "/usr/local/lib/python3.11/dist-packages/uvicorn/middleware/message_logger.py", line 80, in __call__
2024-12-20T15:59:06.215035318Z     await self.app(scope, inner_receive, inner_send)
2024-12-20T15:59:06.215038576Z   File "/usr/local/lib/python3.11/dist-packages/fastapi/applications.py", line 1054, in __call__
2024-12-20T15:59:06.215042184Z     await super().__call__(scope, receive, send)
2024-12-20T15:59:06.215045334Z   File "/usr/local/lib/python3.11/dist-packages/starlette/applications.py", line 113, in __call__
2024-12-20T15:59:06.215049093Z     await self.middleware_stack(scope, receive, send)
2024-12-20T15:59:06.215052830Z   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 165, in __call__
2024-12-20T15:59:06.215056507Z     await self.app(scope, receive, _send)
2024-12-20T15:59:06.215059703Z   File "/app/context_chat_backend/ocs_utils.py", line 79, in __call__
2024-12-20T15:59:06.215063142Z     await self.app(scope, receive, send)
2024-12-20T15:59:06.215066247Z   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-12-20T15:59:06.215070071Z     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-12-20T15:59:06.215073494Z   File "/usr/local/lib/python3.11/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2024-12-20T15:59:06.215077248Z     await app(scope, receive, sender)
2024-12-20T15:59:06.215080410Z   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 715, in __call__
2024-12-20T15:59:06.215084129Z     await self.middleware_stack(scope, receive, send)
2024-12-20T15:59:06.215088259Z   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 735, in app
2024-12-20T15:59:06.215091805Z     await route.handle(scope, receive, send)
2024-12-20T15:59:06.215096340Z   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 288, in handle
2024-12-20T15:59:06.215108284Z     await self.app(scope, receive, send)
2024-12-20T15:59:06.215113882Z   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 76, in app
2024-12-20T15:59:06.215120146Z     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-12-20T15:59:06.215126048Z   File "/usr/local/lib/python3.11/dist-packages/starlette/_exception_handler.py", line 59, in wrapped_app
2024-12-20T15:59:06.215132269Z     response = await handler(conn, exc)
2024-12-20T15:59:06.215137497Z   File "/app/context_chat_backend/controller.py", line 110, in _
2024-12-20T15:59:06.215143055Z     log_error(f'Safe Db Error (user facing): {request.url.path}:', exc)
2024-12-20T15:59:06.215149124Z Message: 'Safe Db Error (user facing): /updateAccessDeclarative:'
2024-12-20T15:59:06.215152659Z Arguments: (SafeDbException('Error: source id not found', 404),)
2024-12-20T15:59:06.215158359Z TRACE:    127.0.0.1:33132 - ASGI [3087] Send {'type': 'http.response.start', 'status': 404, 'headers': '<...>'}
2024-12-20T15:59:06.215189150Z INFO:     127.0.0.1:33132 - "POST /updateAccessDeclarative HTTP/1.1" 404 Not Found
2024-12-20T15:59:06.215332337Z TRACE:    127.0.0.1:33132 - ASGI [3087] Send {'type': 'http.response.body', 'body': '<38 bytes>'}
2024-12-20T15:59:06.215474562Z TRACE:    127.0.0.1:33132 - ASGI [3087] Completed
2024-12-20T15:59:21.226247552Z TRACE:    127.0.0.1:33132 - HTTP connection lost
</details>

nextcloud log
<details>
{"reqId":"p4FHKZ9ac34Q7aKB2kw7","level":3,"time":"2024-12-20T16:59:06+01:00","remoteAddr":"","user":"--","app":"context_chat","method":"","url":"--","message":"Error received from Context Chat Backend (ExApp)","userAgent":"--","version":"30.0.2.3","data":{"app":"context_chat","code":"404","response":"{\"error\":\"Error: source id not found\"}"}}
</details>

**Comment by kyteinsky** [comment]
I don't remember clearly if this was answered in any other issue or not, anyhow,

> updateAccessDeclarative
> Error: source id not found

looks like some share was changed or related file access updates happened before the file was indexed. It's not an issue, when the indexer job picks up the file/folder, it will use the correct user list then, no access updates would be lost.
