### ISSUE TITLE
Help to install this on my Nextcloud server, Debian

### ISSUE THREAD

**Issue by witzker** [nextcloud/context_chat_backend#2]
Hi, I'm new with all this server stuff, so I hope to get help to install this:

1. python -m venv .venv
2. . .venv/bin/activate
3. pip install --no-deps -r reqs.txt
4. Install pandoc from your desired package manager (# apt install pandoc for Debian-based systems)

_Clear so far_

5. Copy example.env to .env and fill in the variables
_How do I find the file during installation and what has to be changed
only This:_
NEXTCLOUD_URL=http://nextcloud.local
right?

7. Configure config.yaml for the model name, model type and its parameters (which also includes model file's path and model id as per requirements, see example config)
_What has to be done here_

8. ./main.py
_Clear so far_

Excuse me for asking, but I really could not find either in Forum nor on YouTube or google any explanation for Dummies.
I'm very excited about this new A.I. features and want to have them working.

If you need more info about my configuration, pls. Let me know.

Hope for patience with a newbie.
THX

**Comment by kyteinsky** [comment]
Hello,  
Thank you for your interest in this project. The setup is very simple: 4 apps need to be installed and you would be good to go.

They are:

1. AppAPI: https://apps.nextcloud.com/apps/app_api
2. Context Chat App: https://apps.nextcloud.com/apps/context_chat
3. Assistant App: https://apps.nextcloud.com/apps/assistant
4. Context Chat Backend App: https://apps.nextcloud.com/apps/context_chat_backend

(NOTE)
The backend app needs to be installed from the "External Apps" page in the top right menu. Others from the regular "Apps" page.

I will update the readme to make it more clear. The steps that you read were to manually install it without using the App Store.

**Comment by witzker** [comment]
Ah...
Many THX for taking care - seems the solution to get this working is near.
I finally got where to find The **Context Chat Backend App**

BUT is grayed out>
![image](https://github.com/nextcloud/context_chat_backend/assets/4120266/2013b895-40c8-4dce-a4bf-2c9b45d71488)

Pls tell me the magic to be able to finally install this.
Many THX

**Comment by kyteinsky** [comment]
It may be because docker isn't installed on your machine or the web server user does not have access to `/var/run/docker.sock`.  
Let me know if that solves the issue. I will add this too to the readme then.

**Comment by witzker** [comment]
So Docker not installed:
root@nextcloud ~# sudo systemctl status docker
Unit docker.service could not be found.
root@nextcloud ~#

Do I have to install docker on my Debian 11 or will it be installed with the apps you mentioned? 
pls. Tell me how to proceed.

**Comment by kyteinsky** [comment]
@witzker You will have to install docker yourself to run any external app (or AppAPI apps) and ensure that the Nextcloud's web server user has access to `/var/run/docker.sock`.  
To check if the configuration is correct, visit the "External Apps" page from the top-right profile icon. If it says "Default Deploy daemon is not accessible", then it is not set up correctly.  
- or -  
In the "Your apps" section in the same page as the screenshot you posted.

**Comment by cnic023** [comment]
I have been following the instructions for Complex Install without docker
I have managed to install and register but, like witzker, I am confused about .env and config.yaml
On executing main.py a service seems to have started which tells me 0 files are being processed. 
**.env**
I assume NEXTCLOUD_URL is http://<IP of host listening on 8080> and that '.local' is just a description that is not meant to be taken literally?
**config.yaml**
"Ensure the config file at persistent_storage/config.yaml points to the correct config file (cpu vs gpu). If you're unsure, delete it. It will be recreated upon launching the application. The default is to point to the gpu config."
I don't have a 'config.yaml' in persistent_storage so I have left it as is. However, I don't have a gpu in my nextcloud install box. My plan is to connect to another server with a gpu so the heavy processing is restricted to that server.
Any help appreciated. I'm trying to avoid docker although I have successfully installed the docker socket proxy on the server with gpu.

**Comment by cnic023** [comment]
Once the context chat backend is running (or seems to be) the last few lines on the monitor say:
 File "/home/chris/ccbkend/context_chat_backend/controller.py", line 121, in background_thread_task
    logger.info(f'Currently indexing {len(_indexing)} documents (filename, size): ', extra={'_indexing': _indexing})
Message: 'Currently indexing 0 documents (filename, size): '
Arguments: ()

**Comment by kyteinsky** [comment]
hello,

> I assume NEXTCLOUD_URL is http://<IP of host listening on 8080> and that '.local' is just a description that is not meant to be taken literally?

yes, that is correct. `.local` is just a domain suffix, the entire thing `http://nextcloud.local` can be replaced with `https://cloud.example.com` or `http://IP:8080` in your case.

> I don't have a 'config.yaml' in persistent_storage so I have left it as is. However, I don't have a gpu in my nextcloud install box. My plan is to connect to another server with a gpu so the heavy processing is restricted to that server.

sorry the readme hasn't been updated for this one. The config file used would be based on the "compute device" selected for the installing daemon if you use you the docker way. For the manual way, it is auto-detected and uses gpu if your server has a NVIDIA GPU. It can be forced to use a certain compute device cpu or gpu by setting `COMPUTE_DEVICE` env var to `CPU` or `CUDA`.

> My plan is to connect to another server with a gpu so the heavy processing is restricted to that server.

If it will be installed there, it will pick up the presence of the gpu automatically and use it.

> Message: 'Currently indexing 0 documents (filename, size): '

that is a debug log and reports the instantaneous indexing status. It will shows some files when the background job starts to work, which should've happened by now.

**Comment by cnic023** [comment]
Thanks very much as this gives me hope to get it working!
Just to summarise, the GPU server will only be doing the large language model work. It has the docker socket proxy installed and registered with ExApp. Its local IP is 192.168.0.250. The other (192.168.0.112) has Nextcloud and all its data installed. I am trying to install context chat backend on 112. My .env file is in the root directory of the venv project for context chat backend. It is:
CC_CONFIG_PATH=persistent_storage/config.yaml
EM_SERVER_LOG_PATH=persistent_storage/logs

# Huggingface offline mode
#TRANSFORMERS_OFFLINE=1

# AppAPI headers
AA_VERSION=4.0.6
APP_SECRET=12345
APP_ID=context_chat_backend
APP_DISPLAY_NAME=Context Chat Backend
APP_VERSION=4.1.0
APP_HOST=192.168.0.112
APP_PORT=10034
APP_PERSISTENT_STORAGE=persistent_storage
NEXTCLOUD_URL=http://192.168.0.112/nextcloud

# CUDA Support
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=compute

Does this look OK to you?

One thing I’m wondering about is that, although Postgresql is running as a service it is not configured. Are there an instructions anywhere to do this or is it OK as is?

Thanks very much for your help.

**Comment by kyteinsky** [comment]
no problem, and thanks to you for trying it out!

these can be removed from the env:
```env
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=compute
```

> One thing I’m wondering about is that, although Postgresql is running as a service it is not configured. Are there an instructions anywhere to do this or is it OK as is?

ah I forgot to add docs for that, will update it soon.

you need `pgvector`, a postgres db vector extension support.
this file contains the manual installation steps for debian: https://github.com/nextcloud/context_chat_backend/blob/master/dockerfile_scripts/pgsql/install.sh
this and other official methods can be found here: https://github.com/pgvector/pgvector?tab=readme-ov-file#installation
there is also the docker way.

the desired username, password and db name can be set/created. The commands we use in the official docker container are: https://github.com/nextcloud/context_chat_backend/blob/006755f99214e793dffac4b7574aed7efc384028/dockerfile_scripts/pgsql/setup.sh#L60-L70
the string values can be run by the admin user in the psql repl as well.

now one more env var needs to be added (replace the placeholders and "localhost"):
```env
CCB_DB_URL="postgresql+psycopg://$CCB_DB_USER:$CCB_DB_PASS@localhost:${PG_PORT}/$CCB_DB_NAME"
```

that should be it. Now the app can be run with `python3 -u ./main.py` or `./main.py`.

**Comment by cnic023** [comment]
Great!! I'll have a try tomorrow

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cnic023** [comment]
I installed pgvector using APT. Following may be useful to someone:

Install pgvector on ubuntu server 22.04 and Postgresql 14.17 using APT

sudo apt install postgresql-server-dev-14

Repository Quickstart

sudo apt install -y postgresql-common
sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh

sudo apt install postgresql-14-pgvector

**Comment by cnic023** [comment]
Took your recommended action. On executing main.py I get following:
“--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.10/logging/handlers.py", line 196, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/chris/ccbkend/context_chat_backend/logger.py", line 56, in format
    message = self._prepare_log_dict(record)
  File "/home/chris/ccbkend/context_chat_backend/logger.py", line 63, in _prepare_log_dict
    record.created, tz=dt.UTC,
AttributeError: module 'datetime' has no attribute 'UTC'”

Nothing is going to ccb.log (assuming it is supposed to)

**Comment by cnic023** [comment]
ccb.log attached. I’m running llama3.1
tcp   LISTEN 0      2048   192.168.0.112:10034      0.0.0.0:*    users:(("python",pid=2154,fd=19))
But nothing listening on:
"protocol": "http",
    "host": "localhost",
    "port": 5000
Hope this makes sense.

**Comment by cnic023** [comment]
Hi Anupam,
I have upgraded to postgresql 17 and context_chat_backend 4.2.0.
When I try to register the app I get:
Daemon config  --force-scopes not found.
The command I used was:
occ app_api:app:register context_chat_backend_manual_install --json-info \
"{\"appid\":\"context_chat_backend\",\"name\":\"Context Chat Backend\",\"daemon_config_name\":\"manual_install\",\"version\":\"4.2.0\",\"secret\":\"12345\",\"port\":10034,\"scopes\":[],\"system_app\":0}" \ --force-scopes --wait-finish
My AppAPI gui looks like this:
***@***.***
Best wishes,
Chris

**Comment by kyteinsky** [comment]
hello,

> AttributeError: module 'datetime' has no attribute 'UTC'”

you should try python 3.11, as that is the min version supported. Sorry about that, it shoud've been in the readme.

> ccb.log attached

seems like the file was not successfully attached.

> occ app_api:app:register context_chat_backend_manual_install --json-info \

there should be a space between "context_chat_backend" and "manual_install" :) 
just fyi, it is not required to re-register the app for upgrades, but if it was a fresh install then it's all good.

> My AppAPI gui looks like this

this image was also not attached it seems.

**Comment by cnic023** [comment]
Strange the log and image did not go through but many thanks for your help. As it happens I had already corrected the error in occ app_api:app:register but found another error! It now tells me the app is registered.

I now have in ExAPI Deploy Daemons:

Docker_local – Docker Local
docker-install

manual_install – Manual Install
manual-install

But I get a warning: “Manual install daemon usually used for development. It cannot be set as default daemon.”

I have installed Python 3.12 and will start again using that to create the venv etc.

Thanks so much for your help
Chris

**Comment by cnic023** [comment]
Context Chat Backend installed now using python3.12. Datetime error has gone. The installation seems sane: reports "Uvicorn running on http://192.168.0.112:10034" (see log)
However, it's not making connection with nextcloud (on same server). Note that the llama install is on a separate server: 192.168.0.250:2375 users:(("haproxy", pid=4194,fd=5))
127.0.0.1:11434 users:(("ollama",pid=1586,fd=3))
Do I need to set up apache2 virtual hosts on both of these servers?

[ccb.log](https://github.com/user-attachments/files/19714120/ccb.log)

**Comment by cnic023** [comment]
Here is my config for deploy daemons and for .env

Deploy Daemon - Docker Local (on 192.168.0.250)
ExApps installed: 1
Name: docker_local
Protocol: http
Host: 192.168.0.250:2375
Deploy config
Docker network: host
Nextcloud URL: https://cloud.nicoll.nz/index.php
HaProxy password: xxxxx
GPUs support: true
Compute device: CUDA (NVIDIA)

Deploy Daemon - Manual Install (on 192.168.0.112)

ExApps installed: 1
Name: manual_install
Protocol: http
Host: localhost
Deploy config
Docker network: host
Nextcloud URL: http://192.168.0.112/nextcloud
GPUs support: false
Compute device: CPU

.env for Context Chat Backend (on 192.168.0.112)

# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# rename this file to .env

# Persistent files directory
# SENTENCE_TRANSFORMERS_HOME=persistent_storage/model_files
# HF_HOME=persistent_storage/model_files
# VECTORDB_DIR=persistent_storage/vector_db_data
CC_CONFIG_PATH=persistent_storage/config.yaml
EM_SERVER_LOG_PATH=persistent_storage/logs

# Huggingface offline mode
#TRANSFORMERS_OFFLINE=1

# AppAPI headers
AA_VERSION=4.0.6
APP_SECRET=12345
APP_ID=context_chat_backend
APP_DISPLAY_NAME=Context Chat Backend
APP_VERSION=4.2.0
APP_HOST=192.168.0.112
APP_PORT=10034
APP_PERSISTENT_STORAGE=persistent_storage
NEXTCLOUD_URL=http://192.168.0.112/nextcloud

CCB_DB_URL="postgresql+psycopg://ccb:xxxxx:5432/ccbdb"
# CUDA Support
#NVIDIA_VISIBLE_DEVICES=all
#NVIDIA_DRIVER_CAPABILITIES=compute

**Comment by kyteinsky** [comment]
> As it happens I had already corrected the error in occ app_api:app:register but found another error! It now tells me the app is registered.

try a clean registration.
```bash
occ app_api:app:unregister --force context_chat_backend
occ app_api:app:register context_chat_backend manual_install --json-info \     
  "{\"id\":\"context_chat_backend\",\"name\":\"Context Chat Backend\",\"daemon_config_name\":\"manual_install\",\"version\":\"4.2.0\",\"secret\":\"12345\",\"port\":10034,\"scopes\":[\"AI_PROVIDERS\"]}" \
  --force-scopes --wait-finish
```

> But I get a warning: “Manual install daemon usually used for development. It cannot be set as default daemon.”

safe to ignore. You probably used the `--set-default` option in daemon registration?

the config looks good but the app is not registered yet.

**Comment by cnic023** [comment]
Tried that and am getting:

ExApp context_chat_backend heartbeat check failed. Make sure that Nextcloud instance and ExApp can reach it other.

**Comment by kyteinsky** [comment]
hello,
sorry for the delay

the config should be correct since manual_install has `host` set to `localhost`, which is `192.168.0.112` where context_chat_backend listens.
still, can you try changing `host` to `192.168.0.112` for the manual_install deploy daemon from admin settings -> AppAPI -> three dots menu of the daemon -> Edit

also pls post the raw server log for the heartbeat error message. It should show the exact URL Nextcloud is trying to reach.

PS. You mentioned that you didn't want to use the GPU server for this app. Would it be possible to have a docker socket proxy container launched in the NC server (`192.168.0.112`)? Select `CPU` for compute device. That would make it quite easier.

**Comment by cnic023** [comment]
Hello,
Nextcloud log says:
ExApp with appId context_chat_backend is disabled (/nextcloud/ocs/v1.php/apps/app_api/ex-app/state?format=json)
I’m wondering if the context_chat_backend app is getting properly registered.
I use the following but don’t get the expected confirmation that registration has happened.
sudo -u www-data php /var/www/html/nextcloud/occ app_api:app:register --json-info "{\"appid\":\"context_chat_backend\",\"name\":\"Context Chat Backend\",\"daemon_config_name\":\"manual_install\",\"version\":\"4.2.0\",\"secret\":\"12345\",\"port\":10034,\"scopes\":[],\"system_app\":0}" --force-scopes --wait-finish context_chat_backend manual_install
I’ve attached the ccb logs

**Comment by kyteinsky** [comment]
looks like the ccb logs were not attached.
And by server logs I meant the nextcloud server logs, they should have the heartbeat attempts logged by the app_api app.

**Comment by cnic023** [comment]
Sorry logs weren't attached. They don't get through when I reply to your emails.

[ccb(1).log](https://github.com/user-attachments/files/20097212/ccb.1.log)
[ccb(2).log](https://github.com/user-attachments/files/20097211/ccb.2.log)
[nextcloud.log](https://github.com/user-attachments/files/20097213/nextcloud.log)

**Comment by kyteinsky** [comment]
not sure how email works with github tbh

thanks for the logs though.
It seems the "host" value of the manual deploy daemon is not set to "192.168.0.112" but to "localhost". Would you mind changing this? See my previous to previous reply.
And is your nextcloud on bare metal or inside docker? The failing request originates in nextcloud and wants to reach context_chat_backend so it would be essential to know this to determine the correct "host" to put in the manual deploy daemon.

**Comment by cnic023** [comment]
Many thanks for your prompt reply.  I have set the manual deploy daemon as instructed:

![Image](https://github.com/user-attachments/assets/72dde076-02e3-488b-8b76-f206ab389de7)

A quick summary of the setup is NC (bare metal) on server A (192.168.0.112). LLM on server B (192.168.0.250) with a docker socket proxy set up by:
docker run -e NC_HAPROXY_PASSWORD="xxx"   -e BIND_ADDRESS="192.168.0.250"   -e EX_APPS_NET=”ipv4@127.0.0.1”   -v /var/run/docker.sock:/var/run/docker.sock   -v `pwd`/certs/cert.pem:/certs/cert.pem   --name nextcloud-appapi-dsp -h nextcloud-appapi-dsp --net host   --restart unless-stopped --privileged -d d11cc2f3da3a

On server A is context_chat_backend although I'm not sure if it has been properly registered. Also on server A, so communications between server A and B can be by http, I have set up the following apache2 http.conf:
<VirtualHost *:80>
        DocumentRoot /var/www/html/nextcloud/
        ServerName 192.168.0.112


        ErrorLog ${APACHE_LOG_DIR}/nextcloud.error
        CustomLog ${APACHE_LOG_DIR}/nextcloud.access combined
<Location />
        Require ip 192.168.0.250
        Require ip 192.168.0.56
        Require local
    </Location>
   
        <Directory /var/www/html/nextcloud/>
            Require all granted
            Options FollowSymLinks MultiViews
            AllowOverride All

       # <IfModule mod_dav.c>
         #   Dav off
         # </IfModule>
         #   Satisfy Any

          <IfModule mod_headers.c>
            Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
         </IfModule>
        </Directory>

     </VirtualHost>

On your last instruction I also setup a docker socket proxy on server A by:

docker run -e NC_HAPROXY_PASSWORD="xxx"   -e BIND_ADDRESS="192.168.0.112"   -e EX_APPS_NET=”ipv4@127.0.0.1”   -v /var/run/docker.sock:/var/run/docker.sock   -v `pwd`/certs/cert.pem:/certs/cert.pem   --name nextcloud-appapi-dsp -h nextcloud-appapi-dsp --net host   --restart unless-stopped --privileged -d d11cc2f3da3a

Trouble is I don't understand how all these components work together and I have little experience with docker. Please excuse my ignorance.

**Comment by cnic023** [comment]
There is now some change as the nexcloud log shows:
{"reqId":"57YcRzHQzuGTSSAjk23L","level":2,"time":"2025-05-09T04:45:07+00:00","remoteAddr":"","user":"--","app":"context_chat","method":"","url":"--","message":"Error performing action \"delete_source_ids\": Context Chat backend is not ready yet. Please wait a while before trying again.","userAgent":"--","version":"30.0.10.1","exception":{"Exception":"RuntimeException","Message":"Context Chat backend is not ready yet. Please wait a while before trying again.","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/context_chat/lib/Service/LangRopeService.php","line":201,"function":"requestToExApp","class":"OCA\\ContextChat\\Service\\LangRopeService","type":"->"},{"file":"/var/www/html/nextcloud/apps/context_chat/lib/BackgroundJobs/ActionJob.php","line":56,"function":"deleteSources","class":"OCA\\ContextChat\\Service\\LangRopeService","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\ContextChat\\BackgroundJobs\\ActionJob","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":43,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":29,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"},{"file":"/var/www/html/nextcloud/cron.php","line":162,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/var/www/html/nextcloud/apps/context_chat/lib/Service/LangRopeService.php","Line":94,"message":"Error performing action \"delete_source_ids\": Context Chat backend is not ready yet. Please wait a while before trying again.","exception":[],"CustomMessage":"Error performing action \"delete_source_ids\": Context Chat backend is not ready yet. Please wait a while before trying again."},"id":"681d8856c3b34"}

**Comment by cnic023** [comment]
I am getting [404] Not found <request: GET /ocs/v1.php/cloud/capabilities
Also when registering context_chat_backend, I get ExApp context_chat_backend deployed successfully. BUT I don't get message that it has been registered.

**Comment by kyteinsky** [comment]
Nice, that's some progress. Nextcloud (app_api) can reach context_chat_backend now.

(edited your comment that contains the apache config to use backticks ```)

> Trouble is I don't understand how all these components work together and I have little experience with docker. Please excuse my ignorance.

no problem. The docker socket proxy is there to expose the docker socket securely to app_api. We send requests to this docker socket to setup the docker containers, pull images, etc. Feel free to reply back if any particular thing does not make sense.

> Context Chat backend is not ready yet. Please wait a while before trying again.

this would mean context_chat_backend is not enabled, which generally happens due to the CC backend not being able to report the progress back to app_api that it is ready, which in-turn would mean that CC backend cannot contact Nextcloud/app_api. CC backend logs would contain the error.
It might be related to the apache config which has an extra `/` in `<Location />` the start tag.
https://httpd.apache.org/docs/current/mod/core.html#location

**Comment by cnic023** [comment]
I am very grateful for your help as I now have a better understanding of how the parts fit together. However, I think I should change the overall configuration to the "Docker on a remote host" deployment in the Nextcloud documentation. I have attached the screenshot.
There are a few things you could advise me about:

- Can the communication between host 1 (nextcloud installation) and host 2 be by http rather than https as I can't be bothered with self-signed certificates etc on an internal lan? Note that Nextcloud host 1 is accessible via a third server (a reverse proxy server open to the Internet). Host 2 would not be directly open to the Internet.
- Am I right in thinking that, with this deployment configuration, the context_chat_backend exapp must be in a docker container on host 2 i.e. NOT manual install?
- My llama installation, also on host 2 (GPU), has been setup. Does this have to be in a container also or can the DSP/AppAPI communicate directly with it? Note that the postgresql server would also be on Host 2
Thanks again.

<img width="572" alt="Image" src="https://github.com/user-attachments/assets/b6a5f8e9-9eca-49d0-a526-a086dfaa0aa4" />

**Comment by kyteinsky** [comment]
1. yes, setup a HTTP (HTTPS unchecked) deploy daemon and set the `OVERRIDE_APP_HOST` (https://docs.nextcloud.com/server/latest/admin_manual/exapps_management/ManagingDeployDaemons.html#additional-options) to the remote server's IP
2. both configurations can work, docker one can be automatically updated
3. context_chat_backend would make use of the LLM through Nextcloud's Text Generation task type which can be facilitated through integration_openai. The postgres server should be reachable by the context_chat_backend container so the ex_app should either be installed with "host" network to access the local postgres, or have postgres in the same docker network as the ex_app.

**Comment by cnic023** [comment]
Sorry I really don’t know how to use docker.
This is what I have done:

  1.  docker pull ghcr.io/nextcloud/context_chat_backend:4.3.0
  2.  edited .env in my local directory
  3.  downloaded Dockerfile to my local directory and edited by adding a line “COPY .env .env” in step 13/34. Also edited ARG CCB_DB_NAME=ccbdb (my database name) ARG CCB_DB_USER=ccb (my database user and ARG CCB_DB_PASS=xxx (my database password).
  4.  When I run docker build -t context_chat_backend . -f Dockerfile I get: “Step 14/34 : ADD dockerfile_scripts/install_deps.sh dockerfile_scripts/install_deps.sh ADD failed: file not found in build context or excluded by .dockerignore: stat dockerfile_scripts/install_deps.sh: file does not exist”
My .env is:
AA_VERSION=4.0.6
APP_SECRET=12345
APP_ID=context_chat_backend
APP_DISPLAY_NAME=Context Chat Backend
APP_VERSION=4.3.0
APP_HOST=192.168.0.250
APP_PORT=10034
APP_PERSISTENT_STORAGE=persistent_storage
NEXTCLOUD_URL=http://192.168.0.112
CCB_DB_URL="postgresql+psycopg://ccb:xxxxxx:5432/ccbdb" (redact password)
CUDA Support
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=compute

**Comment by kyteinsky** [comment]
I would recommend to use a second docker socket proxy on the other host with CPU as the compute type. It is much easier and would update the app automatically too. You would just need to have docker installed there.

> When I run docker build -t context_chat_backend . -f Dockerfile I get: “Step 14/34 : ADD dockerfile_scripts/install_deps.sh dockerfile_scripts/install_deps.sh ADD failed: file not found in build context or excluded by .dockerignore: stat dockerfile_scripts/install_deps.sh: file does not exist”

you would need almost all of this repository (a clone) to build the docker image so downloading the complete thing is the way to go. In the error above, it needs the `dockerfile_scripts` folder but later instructions need other files that are in this repo.

**Comment by cnic023** [comment]
I have cloned the ccb repo (docker clone) and cd to context_chat_backend, edited example.env and did:
docker build -t context_chat_backend . -f Dockerfile
The result is always the same as described in my last email. The final message is:
Step 30/33 : COPY config.?pu.yaml .
When using COPY with more than one source file, the destination must be a directory and end with a /

**Comment by witzker** [comment]
Hi everyone,
Crazy, right?!
After the feature announcement, I'm really hoping for a step-by-step guide.
How far along are we?

**Comment by cnic023** [comment]
I think the other problem was that I have my Nextcloud installation on server A (cpu) and my LLM on server B (gpu). I am happy to use docker as, by now, I am a newbie but not a complete newbie.
Thanks for all your help. It would be great to get this working but maybe I should wait a bit?

**Comment by kyteinsky** [comment]
hey @cnic023, https://github.com/nextcloud/context_chat_backend/issues/2#issuecomment-3037459248 this message was meant for @witzker, sorry for the confusion.
This was my message for you: https://github.com/nextcloud/context_chat_backend/issues/2#issuecomment-3035083119

**Comment by witzker** [comment]
OK THX
Long and winding road
But is it worth it?
 In the meantime, I installed Anything LLM with 64 MB Model locally but am really disappointed with the results.
Which Model did you use?
Local one?
Is it possible to use a free A.I. for this?
