### ISSUE TITLE
Understanding nc_texttotext and models needed files

### ISSUE THREAD

**Issue by tuxArg** [nextcloud/context_chat_backend#88]
I'm implementing different AI models using app_api and docker_socket_proxy. I'm doing all this without giving docker containers access to the outside world. So I download all models and then I run it in an internal docker network with a proxy to my NC installation.
I have successfully deployed this way many exApps: llm2, translate2 and stt_whisper2.

But I'm having really hard time getting this app working. If I understand it correctly I can use my llm2 working exapp to use it as a text2text provider for context_chat_backend. And no models have to be downloaded? I'm using the default config.yaml

I've got this error:
```Traceback (most recent call last):
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/middleware\/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "\/app\/context_chat_backend\/ocs_utils.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/middleware\/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/fastapi\/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/fastapi\/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/starlette\/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/anyio\/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/anyio\/_backends\/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/anyio\/_backends\/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/app\/context_chat_backend\/utils.py", line 74, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "\/app\/context_chat_backend\/controller.py", line 347, in _
    return execute_query(query)
           ^^^^^^^^^^^^^^^^^^^^
  File "\/app\/context_chat_backend\/controller.py", line 319, in execute_query
    return process_context_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "\/app\/context_chat_backend\/chain\/one_shot.py", line 72, in process_context_query
    get_pruned_query(llm, app_config, query, template or _LLM_TEMPLATE, context_chunks),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/app\/context_chat_backend\/chain\/query_proc.py", line 32, in get_pruned_query
    query_tokens = llm.get_num_tokens(query)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/langchain_core\/language_models\/base.py", line 335, in get_num_tokens
    return len(self.get_token_ids(text))
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/langchain_core\/language_models\/base.py", line 322, in get_token_ids
    return _get_token_ids_default_method(text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/langchain_core\/language_models\/base.py", line 57, in _get_token_ids_default_method
    tokenizer = get_tokenizer()
                ^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/langchain_core\/language_models\/base.py", line 51, in get_tokenizer
    return GPT2TokenizerFast.from_pretrained("gpt2")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\/usr\/local\/lib\/python3.11\/dist-packages\/transformers\/tokenization_utils_base.py", line 2094, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'gpt2'. If you were trying to load it from 'https:\/\/huggingface.co\/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'gpt2' is the correct path to a directory containing all relevant files for a GPT2TokenizerFast tokenizer.
```

Does that it means that I need a gpt2 model anyway? If that is true, how can I manually download it and where do I have to place it?

Thanks

**Comment by kyteinsky** [comment]
Hi, that's a nice setup. It seems when we transitioned from in-container llama llm model to using the task processing provider with nc_texttotext, this function was left out and rightfully so since there is no task type for that yet (not sure if we will add it later), it uses a fallback tokenizer which is GPT2's fast tokenizer.
The tokenizer is only used for getting an estimate of the size of the text, it does not affect the output (directly or significantly).
And to answer your final question, yes, it needs to be downloaded. Inside the container or anywhere with internet access and "huggingface-cli" installed, you can run:
```
HF_HOME=/nc_app_context_chat_backend_data/model_files huggingface-cli download gpt2 config.json merges.txt tokenizer.json tokenizer_config.json vocab.json
```
to download the necessary files. Change `HF_HOME` to something else if outside the container but move the `hub/` folder in `/nc_app_context_chat_backend_data/model_files` afterwards.

**Comment by tuxArg** [comment]
That worked, thanks!
