### ISSUE TITLE
[bug]: context_chat_backend/models/__init__.py has instructor model reference

### ISSUE THREAD

**Issue by ga-it** [nextcloud/context_chat_backend#92]
**Describe the bug**
context_chat_backend/models/__init__.py still contains "instructor" in its embedding models. This causes a 500 error when the backend attempts to load the models

Line 7: _embedding_models = ["llama", "hugging_face", "instructor"]

**To Reproduce**
1. Start the context_backend_chat container
2. From the assistant, launch a context chat query
3. Receive 500 error when model fail to load

**Expected behavior**
The instructor model reference needs to be removed to that models load correctly.

**Context Chat Backend logs (if applicable, from the docker container)**
<details>
```
--- Logging error ---
Traceback (most recent call last):
  File "/app/context_chat_backend/models/__init__.py", line 22, in load_model
    module = import_module(f".{model_name}", "context_chat_backend.models")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'context_chat_backend.models.instructor'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/context_chat_backend/models/__init__.py", line 49, in init_model
    model = load_model(model_type, model_info)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/context_chat_backend/models/__init__.py", line 24, in load_model
    raise AssertionError(f"Error: could not load {model_name} model from context_chat_backend/models") from e
AssertionError: Error: could not load instructor model from context_chat_backend/models

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/context_chat_backend/dyn_loader.py", line 77, in load
    model = init_model('embedding', self.config['embedding'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/context_chat_backend/models/__init__.py", line 51, in init_model
    raise AssertionError(f"Error: {model_name} failed to load") from e
AssertionError: Error: instructor failed to load

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/context_chat_backend/controller.py", line 123, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/context_chat_backend/controller.py", line 361, in _
    return execute_query(query)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/context_chat_backend/controller.py", line 329, in execute_query
    db: BaseVectorDB = vectordb_loader.load()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/context_chat_backend/dyn_loader.py", line 57, in load
    embedding_model = EmbeddingModelLoader(self.app, self.config).load()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/context_chat_backend/dyn_loader.py", line 79, in load
    raise LoaderException() from e
context_chat_backend.dyn_loader.LoaderException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/main.py", line 16, in <module>
    uvicorn.run(
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/middleware/message_logger.py", line 80, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/local/lib/python3.11/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/app/context_chat_backend/ocs_utils.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/_exception_handler.py", line 59, in wrapped_app
    response = await handler(conn, exc)
  File "/app/context_chat_backend/controller.py", line 86, in _
    log_error(f'Loader Error: {request.url.path}:', exc)
Message: 'Loader Error: /query:'
Arguments: (LoaderException(),)
TRACE:    x:43818 - ASGI [4] Send {'type': 'http.response.start', 'status': 500, 'headers': '<...>'}
INFO:     x:43818 - "POST /query HTTP/1.1" 500 Internal Server Error
TRACE:    x:43818 - ASGI [4] Send {'type': 'http.response.body', 'body': '<90 bytes>'}
TRACE:    x:43818 - ASGI [4] Completed
TRACE:    x:43818 - HTTP connection lost

```
</details>

 - Nextcloud Version: 30.0.1 - 30.0.1.2
 - AppAPI Version: 4.0.0
 - Context Chat PHP Version 3.1.0
 - Context Chat Backend Version 3.1.0
 - Nextcloud deployment method: Docker
 - Context Chat Backend deployment method: manual, remote

**Comment by kyteinsky** [comment]
Hi, you seem to be using the master branch. These issues are expected since we have not added the config repair steps yet, they are included when a release is done. If you're using context chat in production, I'd advice to use only the released versions.

This can be fixed using this command that removes the old config and rebooting the container:
```
docker exec nc_app_context_chat_backend rm /nc_app_context_chat_backend_data/config.yaml
```

**Comment by ga-it** [comment]
Here is the current config.yaml:

```
/app# cat config.yaml
debug: true
disable_aaa: false
httpx_verify_ssl: true
model_offload_timeout: 15 # 15 minutes
use_colors: true
uvicorn_workers: 1
embedding_chunk_size: 1000

# model files download configuration
disable_custom_model_download: false
model_download_uri: https://download.nextcloud.com/server/apps/context_chat_backend


vectordb:
  chroma:
    is_persistent: true
    # chroma_server_host:
    # chroma_server_http_port:
    # chroma_server_ssl_enabled:
    # chroma_server_api_default_path:

  pgvector:
    connection: postgresql+psycopg://ccbuser:ccbpass@localhost:5432/ccb

  weaviate:
    # auth_client_secret:
    # url: http://localhost:8080

embedding:
  instructor:
    model_name: hkunlp/instructor-base
    model_kwargs:
      device: cuda

  llama:
    model_path: multilingual-e5-large-instruct-q6_k.gguf
    n_batch: 512
    n_ctx: 8192
    n_gpu_layers: -1

  hugging_face:
    model_name: nextcloud-ai/multilingual-e5-large-instruct
    model_kwargs:
      device: cuda

llm:
  nc_texttotext:

  llama:
    model_path: dolphin-2.2.1-mistral-7b.Q5_K_M.gguf
    n_batch: 512
    n_ctx: 8192
    max_tokens: 4096
    template: "<|im_start|> system \nYou're an AI assistant named Nextcloud Assistant, good at finding relevant context from documents to answer questions provided by the user. <|im_end|>\n<|im_start|> user\nUse the following documents as context to answer the question at the end. REMEMBER to excersice source critisicm as the documents are returned by a search provider that can return unrelated documents.\n\nSTART OF CONTEXT: \n{context} \n\nEND OF CONTEXT!\n\nIf you don't know the answer or are unsure, just say that you don't know, don't try to make up an answer. Don't mention the context in your answer but rather just answer the question directly.  Detect the language of the question and make sure to use the same language that was used in the question to answer the question. Don't mention which language was used, but just answer the question directly in the same langauge. \nQuestion: {question} Let's think this step-by-step. \n<|im_end|>\n<|im_start|> assistant\n"
    no_ctx_template: "<|im_start|> system \nYou're an AI assistant named Nextcloud Assistant.<|im_end|>\n<|im_start|> user\n{question}<|im_end|>\n<|im_start|> assistant\n"
    end_separator: "<|im_end|>"
    n_gpu_layers: -1
    model_kwargs:
      device: cuda

  ctransformer:
    model: dolphin-2.2.1-mistral-7b.Q5_K_M.gguf
    template: "<|im_start|> system \nYou're an AI assistant named Nextcloud Assistant, good at finding relevant context from documents to answer questions provided by the user. <|im_end|>\n<|im_start|> user\nUse the following documents as context to answer the question at the end. REMEMBER to excersice source critisicm as the documents are returned by a search provider that can return unrelated documents.\n\nSTART OF CONTEXT: \n{context} \n\nEND OF CONTEXT!\n\nIf you don't know the answer or are unsure, just say that you don't know, don't try to make up an answer. Don't mention the context in your answer but rather just answer the question directly.  Detect the language of the question and make sure to use the same language that was used in the question to answer the question. Don't mention which language was used, but just answer the question directly in the same langauge. \nQuestion: {question} Let's think this step-by-step. \n<|im_end|>\n<|im_start|> assistant\n"
    no_ctx_template: "<|im_start|> system \nYou're an AI assistant named Nextcloud Assistant.<|im_end|>\n<|im_start|> user\n{question}<|im_end|>\n<|im_start|> assistant\n"
    end_separator: "<|im_end|>"
    config:
      context_length: 8192
      max_new_tokens: 4096
      local_files_only: True
      gpu_layers: -1

  hugging_face:
    model_id: gpt2
    task: text-generation
    pipeline_kwargs:
      config:
        max_length: 200
    template: ""
```

**Comment by kyteinsky** [comment]
I'd suggest to install the tagged version 3.1.0 and let the config be as is.

**Comment by kyteinsky** [comment]
Closing this issue since instructor was completely removed in the latest version.
